name: Run unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Instalar dependências
        run: |
          go mod tidy

      - name: Rodar testes
        run: |
          go test ./...
